<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-KVV4E8PT" failures="1" tests="5" name="Test" time="28.638" errors="0" timestamp="2022-11-02T20:46:44 IST">
  <testcase classname="Amazontestng123.NewTest" name="a3" time="1.401"/>
  <testcase classname="Amazontestng123.NewTest" name="a5" time="4.681"/>
  <testcase classname="Amazontestng123.NewTest" name="a4" time="1.437"/>
  <testcase classname="Amazontestng123.NewTest12" name="a3" time="1.997"/>
  <testcase classname="Amazontestng123.NewTest12" name="a5" time="1.536">
    <failure type="java.lang.AssertionError" message="expected [https://www.amazon.in/events/greatindianfestival?ref_=nav_cs_gb1] but found [https://www.amazon.in/events/greatindianfestival?ref_=nav_cs_gb]">
      <![CDATA[java.lang.AssertionError: expected [https://www.amazon.in/events/greatindianfestival?ref_=nav_cs_gb1] but found [https://www.amazon.in/events/greatindianfestival?ref_=nav_cs_gb]
at Amazontestng123.NewTest12.a5(NewTest12.java:53)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- a5 -->
</testsuite> <!-- Test -->
